# Generated by Django 5.0.6 on 2024-07-29 19:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=100, unique=True)),
                ('artists', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True), blank=True, default=list, null=True, size=None)),
                ('friends', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True), blank=True, default=list, null=True, size=None)),
                ('display_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
