# Generated by Django 5.0.6 on 2024-07-06 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_artist_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artist_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True), blank=True, default=list, null=True, size=None),
        ),
    ]
