# Generated by Django 5.0.6 on 2024-07-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_artist_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='artist_list',
            new_name='artists',
        ),
    ]
