# Generated by Django 5.0.6 on 2024-07-30 18:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='artists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, null=True, size=None, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, default=list, null=True, size=None, unique=True),
        ),
    ]
