# Generated by Django 5.0.6 on 2024-07-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_artist_list_user_artists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
